<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33861" started-at="2019-02-19T18:46:37Z" finished-at="2019-02-19T18:47:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33861" started-at="2019-02-19T18:46:37Z" finished-at="2019-02-19T18:47:11Z">
      <class name="org.devops.udemy.demoproject.TestClass1">
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="launchDriver" is-config="true" duration-ms="5963" started-at="2019-02-19T18:46:37Z" finished-at="2019-02-19T18:46:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="Test1" duration-ms="5080" started-at="2019-02-19T18:46:43Z" finished-at="2019-02-19T18:46:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="quit" is-config="true" duration-ms="3881" started-at="2019-02-19T18:46:48Z" finished-at="2019-02-19T18:46:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="launchDriver" is-config="true" duration-ms="3687" started-at="2019-02-19T18:46:52Z" finished-at="2019-02-19T18:46:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="FAIL" signature="Test2()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="Test2" duration-ms="4589" started-at="2019-02-19T18:46:56Z" finished-at="2019-02-19T18:47:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [NoDQ - Wrestling PodCat] but found [NoDQ - Wrestling PodCast]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [NoDQ - Wrestling PodCat] but found [NoDQ - Wrestling PodCast]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.devops.udemy.demoproject.TestClass1.Test2(TestClass1.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="quit" is-config="true" duration-ms="1436" started-at="2019-02-19T18:47:00Z" finished-at="2019-02-19T18:47:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="launchDriver" is-config="true" duration-ms="3809" started-at="2019-02-19T18:47:02Z" finished-at="2019-02-19T18:47:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="PASS" signature="Test3()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="Test3" duration-ms="3929" started-at="2019-02-19T18:47:05Z" finished-at="2019-02-19T18:47:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@6950e31]" name="quit" is-config="true" duration-ms="1443" started-at="2019-02-19T18:47:09Z" finished-at="2019-02-19T18:47:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- org.devops.udemy.demoproject.TestClass1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
