<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="45870" started-at="2019-03-10T20:00:34Z" finished-at="2019-03-10T20:01:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="45870" started-at="2019-03-10T20:00:34Z" finished-at="2019-03-10T20:01:20Z">
      <class name="org.devops.udemy.demoproject.TestClass1">
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="launchDriver" is-config="true" duration-ms="18691" started-at="2019-03-10T20:00:34Z" finished-at="2019-03-10T20:00:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="PASS" signature="Test1()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="Test1" duration-ms="5434" started-at="2019-03-10T20:00:53Z" finished-at="2019-03-10T20:00:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test1 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="quit" is-config="true" duration-ms="415" started-at="2019-03-10T20:00:58Z" finished-at="2019-03-10T20:00:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="launchDriver" is-config="true" duration-ms="6407" started-at="2019-03-10T20:00:59Z" finished-at="2019-03-10T20:01:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="FAIL" signature="Test2()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="Test2" duration-ms="4133" started-at="2019-03-10T20:01:05Z" finished-at="2019-03-10T20:01:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at org.devops.udemy.demoproject.TestClass1.Test2(TestClass1.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test2 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="quit" is-config="true" duration-ms="224" started-at="2019-03-10T20:01:09Z" finished-at="2019-03-10T20:01:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="launchDriver()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="launchDriver" is-config="true" duration-ms="6196" started-at="2019-03-10T20:01:10Z" finished-at="2019-03-10T20:01:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method status="PASS" signature="Test3()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="Test3" duration-ms="4101" started-at="2019-03-10T20:01:16Z" finished-at="2019-03-10T20:01:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test3 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:org.devops.udemy.demoproject.TestClass1@7cbd213e]" name="quit" is-config="true" duration-ms="246" started-at="2019-03-10T20:01:20Z" finished-at="2019-03-10T20:01:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- org.devops.udemy.demoproject.TestClass1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
